apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: icloud
resources:
- ../../base
images:
- name: nginx
  newName: mysql
  newTag: 8
buildMetadata: [managedByLabel]
commonAnnotations:
  oncallPager: mujianmin
commonLabels:
  keep: GO
configMapGenerator:
- name: my-java-server-env-vars
  literals:
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof
  options:
    disableNameSuffixHash: true
    labels:
      pet: dog
