apiVersion: apps/v1
kind: Deployment
metadata:
  name: mucloud
  annotations:
    app: beijing
spec:
  selector:
    matchLabels:
      app: mucloud
  template:
    metadata:
      labels:
        app: mucloud
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
